---
- hosts: hw1
  remote_user: ubuntu
  become: yes
  become_method: sudo
  tasks:
    - name: install apache2
      apt: name=apache2 update_cache=yes state=latest
    - name: clone hw0 repo
      git: repo=https://github.com/ketsai/cloud-computing-instance.git dest=/var/www/html/
    - name: start apache2
      service: name=apache2 state=started
